stages:
  - build
  - make_docker
  - trigger

make_snapshot:
  stage: build
  image: wizni/maven:3.3.3
  script:
   - ( cd DataGenerator; mvn clean install )
   - mvn clean package -DskipTests -Dcheckstyle.skip -Pbuild-distr
   - cp zeppelin-distribution/target/zeppelin*.tar.gz /snapshots/
  artifacts:
   name: "zeppelin_${CI_BUILD_REF_NAME}"
   paths:
   - zeppelin-distribution/target/zeppelin*.tar.gz

make_docker:
  stage: make_docker
  image: docker:latest
  services:
  - docker:dind
  script:
  - tar -zxf  $CI_PROJECT_DIR/zeppelin-distribution/target/zeppelin-0.6.0-incubating-SNAPSHOT.tar.gz -C $CI_PROJECT_DIR/
  - docker build -t wizni/zeppelin:test .
  - docker push wizni/zeppelin:test

test_deploy:
  stage: trigger
  image: wizni/maven:3.3.3
  script:
    - "curl -X POST -F token=${TEST_DEPLOY_TOKEN} -F ref=master http://188.166.190.20/api/v3/projects/7/trigger/builds"
